name: Log ISS Location Data Daily

on:
  schedule:
    # Runs at 12:00 UTC (noon) every day
    - cron: "0 12 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache Python packages (repo-relative folder)
      - name: Cache Python packages
        id: cache-step
        uses: actions/cache@v4
        with:
          path: .uv          # relative to repo root
          key: cache-d9751e1

      # Step 3: Prime cache
      - name: prime-cache-d9751e1
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Step 4: Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # Step 5: Fetch ISS location data
      - name: Fetch ISS location data
        run: |
          uv run --with requests pytho
